### PR TITLE
added a macro to remove group names

### PR DESCRIPTION
**Pull request by Ahmad-Fuad**

### CODE REVIEW

**Comment by Ahmad-Fuad** [comment]
@alepietrobon kindly review the first part of the macros ona-utils work

**Review by alepietrobon — COMMENTED** [review]
Can you add another optional parameter for "exclude_columns"? So we can pass an extra list of columns where the group name should not be processed. The default for the argument is NULL

**Comment by Ahmad-Fuad** [comment]
@alepietrobon updated to include column exceptions [here](https://github.com/onaio/dbt-ona-utils/pull/14/commits/4063cc20a7e820a839bb7a808b135697cfea5034) and updated to latest dbt utils version [here](https://github.com/onaio/dbt-ona-utils/pull/14/commits/ce0d72180ac5c2de42ab4518941dc532f4ea1e92)

**Review by alepietrobon — APPROVED** [review]
yup, i haven't tested fully it but it looks right now. Onwards and upwards

**Pull request merged**
